export function findHeroInfo(hero_id: number) {
  return heroesStaticData.find((el) => el.id === hero_id);
}

const heroesStaticData: {
  id: number;
  name: string;
  primary_attr: 'agi' | 'str' | 'int' | 'all';
  attack_type: string;
  roles: string[];
  img: string;
  icon: string;
  localized_name: string;
}[] = [
  {
    id: 1,
    name: 'npc_dota_hero_antimage',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/antimage.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/antimage.png?',
    localized_name: 'Anti-Mage',
  },
  {
    id: 2,
    name: 'npc_dota_hero_axe',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Initiator', 'Durable', 'Disabler', 'Carry'],
    img: '/apps/dota2/images/dota_react/heroes/axe.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/axe.png?',
    localized_name: 'Axe',
  },
  {
    id: 3,
    name: 'npc_dota_hero_bane',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/bane.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/bane.png?',

    localized_name: 'Bane',
  },
  {
    id: 4,
    name: 'npc_dota_hero_bloodseeker',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Disabler', 'Nuker', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/bloodseeker.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/bloodseeker.png?',
    localized_name: 'Bloodseeker',
  },
  {
    id: 5,
    name: 'npc_dota_hero_crystal_maiden',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/crystal_maiden.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/crystal_maiden.png?',
    localized_name: 'Crystal Maiden',
  },
  {
    id: 6,
    name: 'npc_dota_hero_drow_ranger',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Disabler', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/drow_ranger.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/drow_ranger.png?',
    localized_name: 'Drow Ranger',
  },
  {
    id: 7,
    name: 'npc_dota_hero_earthshaker',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Support', 'Initiator', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/earthshaker.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/earthshaker.png?',
    localized_name: 'Earthshaker',
  },
  {
    id: 8,
    name: 'npc_dota_hero_juggernaut',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Pusher', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/juggernaut.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/juggernaut.png?',
    localized_name: 'Juggernaut',
  },
  {
    id: 9,
    name: 'npc_dota_hero_mirana',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Carry', 'Support', 'Escape', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/mirana.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/mirana.png?',
    localized_name: 'Mirana',
  },
  {
    id: 10,
    name: 'npc_dota_hero_morphling',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Escape', 'Durable', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/morphling.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/morphling.png?',
    localized_name: 'Morphling',
  },
  {
    id: 11,
    name: 'npc_dota_hero_nevermore',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/nevermore.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/nevermore.png?',
    localized_name: 'Shadow Fiend',
  },
  {
    id: 12,
    name: 'npc_dota_hero_phantom_lancer',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Pusher', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/phantom_lancer.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/phantom_lancer.png?',
    localized_name: 'Phantom Lancer',
  },
  {
    id: 13,
    name: 'npc_dota_hero_puck',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Initiator', 'Disabler', 'Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/puck.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/puck.png?',
    localized_name: 'Puck',
  },
  {
    id: 14,
    name: 'npc_dota_hero_pudge',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Disabler', 'Initiator', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/pudge.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/pudge.png?',
    localized_name: 'Pudge',
  },
  {
    id: 15,
    name: 'npc_dota_hero_razor',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Durable', 'Nuker', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/razor.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/razor.png?',
    localized_name: 'Razor',
  },
  {
    id: 16,
    name: 'npc_dota_hero_sand_king',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Initiator', 'Disabler', 'Support', 'Nuker', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/sand_king.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/sand_king.png?',
    localized_name: 'Sand King',
  },
  {
    id: 17,
    name: 'npc_dota_hero_storm_spirit',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Escape', 'Nuker', 'Initiator', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/storm_spirit.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/storm_spirit.png?',
    localized_name: 'Storm Spirit',
  },
  {
    id: 18,
    name: 'npc_dota_hero_sven',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/sven.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/sven.png?',
    localized_name: 'Sven',
  },
  {
    id: 19,
    name: 'npc_dota_hero_tiny',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Nuker', 'Pusher', 'Initiator', 'Durable', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/tiny.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/tiny.png?',
    localized_name: 'Tiny',
  },
  {
    id: 20,
    name: 'npc_dota_hero_vengefulspirit',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Initiator', 'Disabler', 'Nuker', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/vengefulspirit.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/vengefulspirit.png?',
    localized_name: 'Vengeful Spirit',
  },
  {
    id: 21,
    name: 'npc_dota_hero_windrunner',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Carry', 'Support', 'Disabler', 'Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/windrunner.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/windrunner.png?',
    localized_name: 'Windranger',
  },
  {
    id: 22,
    name: 'npc_dota_hero_zuus',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Nuker', 'Carry'],
    img: '/apps/dota2/images/dota_react/heroes/zuus.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/zuus.png?',
    localized_name: 'Zeus',
  },
  {
    id: 23,
    name: 'npc_dota_hero_kunkka',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Support', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/kunkka.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/kunkka.png?',
    localized_name: 'Kunkka',
  },
  {
    id: 25,
    name: 'npc_dota_hero_lina',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Carry', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/lina.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/lina.png?',
    localized_name: 'Lina',
  },
  {
    id: 26,
    name: 'npc_dota_hero_lion',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/lion.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/lion.png?',
    localized_name: 'Lion',
  },
  {
    id: 27,
    name: 'npc_dota_hero_shadow_shaman',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Pusher', 'Disabler', 'Nuker', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/shadow_shaman.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/shadow_shaman.png?',
    localized_name: 'Shadow Shaman',
  },
  {
    id: 28,
    name: 'npc_dota_hero_slardar',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Durable', 'Initiator', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/slardar.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/slardar.png?',
    localized_name: 'Slardar',
  },
  {
    id: 29,
    name: 'npc_dota_hero_tidehunter',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Initiator', 'Durable', 'Disabler', 'Nuker', 'Carry'],
    img: '/apps/dota2/images/dota_react/heroes/tidehunter.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/tidehunter.png?',
    localized_name: 'Tidehunter',
  },
  {
    id: 30,
    name: 'npc_dota_hero_witch_doctor',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/witch_doctor.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/witch_doctor.png?',
    localized_name: 'Witch Doctor',
  },
  {
    id: 31,
    name: 'npc_dota_hero_lich',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/lich.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/lich.png?',
    localized_name: 'Lich',
  },
  {
    id: 32,
    name: 'npc_dota_hero_riki',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/riki.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/riki.png?',
    localized_name: 'Riki',
  },
  {
    id: 33,
    name: 'npc_dota_hero_enigma',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Disabler', 'Initiator', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/enigma.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/enigma.png?',
    localized_name: 'Enigma',
  },
  {
    id: 34,
    name: 'npc_dota_hero_tinker',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/tinker.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/tinker.png?',
    localized_name: 'Tinker',
  },
  {
    id: 35,
    name: 'npc_dota_hero_sniper',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/sniper.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/sniper.png?',
    localized_name: 'Sniper',
  },
  {
    id: 36,
    name: 'npc_dota_hero_necrolyte',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Durable', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/necrolyte.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/necrolyte.png?',
    localized_name: 'Necrophos',
  },
  {
    id: 37,
    name: 'npc_dota_hero_warlock',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Initiator', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/warlock.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/warlock.png?',
    localized_name: 'Warlock',
  },
  {
    id: 38,
    name: 'npc_dota_hero_beastmaster',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Initiator', 'Disabler', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/beastmaster.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/beastmaster.png?',
    localized_name: 'Beastmaster',
  },
  {
    id: 39,
    name: 'npc_dota_hero_queenofpain',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/queenofpain.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/queenofpain.png?',
    localized_name: 'Queen of Pain',
  },
  {
    id: 40,
    name: 'npc_dota_hero_venomancer',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Initiator', 'Pusher', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/venomancer.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/venomancer.png?',
    localized_name: 'Venomancer',
  },
  {
    id: 41,
    name: 'npc_dota_hero_faceless_void',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Initiator', 'Disabler', 'Escape', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/faceless_void.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/faceless_void.png?',
    localized_name: 'Faceless Void',
  },
  {
    id: 42,
    name: 'npc_dota_hero_skeleton_king',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Support', 'Durable', 'Disabler', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/skeleton_king.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/skeleton_king.png?',
    localized_name: 'Wraith King',
  },
  {
    id: 43,
    name: 'npc_dota_hero_death_prophet',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Pusher', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/death_prophet.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/death_prophet.png?',
    localized_name: 'Death Prophet',
  },
  {
    id: 44,
    name: 'npc_dota_hero_phantom_assassin',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/phantom_assassin.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/phantom_assassin.png?',
    localized_name: 'Phantom Assassin',
  },
  {
    id: 45,
    name: 'npc_dota_hero_pugna',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Nuker', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/pugna.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/pugna.png?',
    localized_name: 'Pugna',
  },
  {
    id: 46,
    name: 'npc_dota_hero_templar_assassin',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/templar_assassin.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/templar_assassin.png?',
    localized_name: 'Templar Assassin',
  },
  {
    id: 47,
    name: 'npc_dota_hero_viper',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Durable', 'Initiator', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/viper.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/viper.png?',
    localized_name: 'Viper',
  },
  {
    id: 48,
    name: 'npc_dota_hero_luna',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/luna.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/luna.png?',
    localized_name: 'Luna',
  },
  {
    id: 49,
    name: 'npc_dota_hero_dragon_knight',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Pusher', 'Durable', 'Disabler', 'Initiator', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/dragon_knight.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/dragon_knight.png?',
    localized_name: 'Dragon Knight',
  },
  {
    id: 50,
    name: 'npc_dota_hero_dazzle',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/dazzle.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/dazzle.png?',
    localized_name: 'Dazzle',
  },
  {
    id: 51,
    name: 'npc_dota_hero_rattletrap',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Initiator', 'Disabler', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/rattletrap.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/rattletrap.png?',
    localized_name: 'Clockwerk',
  },
  {
    id: 52,
    name: 'npc_dota_hero_leshrac',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Support', 'Nuker', 'Pusher', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/leshrac.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/leshrac.png?',
    localized_name: 'Leshrac',
  },
  {
    id: 53,
    name: 'npc_dota_hero_furion',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Pusher', 'Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/furion.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/furion.png?',
    localized_name: "Nature's Prophet",
  },
  {
    id: 54,
    name: 'npc_dota_hero_life_stealer',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Durable', 'Escape', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/life_stealer.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/life_stealer.png?',
    localized_name: 'Lifestealer',
  },
  {
    id: 55,
    name: 'npc_dota_hero_dark_seer',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Initiator', 'Escape', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/dark_seer.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/dark_seer.png?',
    localized_name: 'Dark Seer',
  },
  {
    id: 56,
    name: 'npc_dota_hero_clinkz',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Escape', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/clinkz.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/clinkz.png?',
    localized_name: 'Clinkz',
  },
  {
    id: 57,
    name: 'npc_dota_hero_omniknight',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Support', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/omniknight.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/omniknight.png?',
    localized_name: 'Omniknight',
  },
  {
    id: 58,
    name: 'npc_dota_hero_enchantress',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Pusher', 'Durable', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/enchantress.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/enchantress.png?',
    localized_name: 'Enchantress',
  },
  {
    id: 59,
    name: 'npc_dota_hero_huskar',
    primary_attr: 'str',
    attack_type: 'Ranged',
    roles: ['Carry', 'Durable', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/huskar.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/huskar.png?',
    localized_name: 'Huskar',
  },
  {
    id: 60,
    name: 'npc_dota_hero_night_stalker',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Initiator', 'Durable', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/night_stalker.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/night_stalker.png?',
    localized_name: 'Night Stalker',
  },
  {
    id: 61,
    name: 'npc_dota_hero_broodmother',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Carry', 'Pusher', 'Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/broodmother.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/broodmother.png?',
    localized_name: 'Broodmother',
  },
  {
    id: 62,
    name: 'npc_dota_hero_bounty_hunter',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/bounty_hunter.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/bounty_hunter.png?',
    localized_name: 'Bounty Hunter',
  },
  {
    id: 63,
    name: 'npc_dota_hero_weaver',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/weaver.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/weaver.png?',
    localized_name: 'Weaver',
  },
  {
    id: 64,
    name: 'npc_dota_hero_jakiro',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Pusher', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/jakiro.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/jakiro.png?',
    localized_name: 'Jakiro',
  },
  {
    id: 65,
    name: 'npc_dota_hero_batrider',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Initiator', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/batrider.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/batrider.png?',
    localized_name: 'Batrider',
  },
  {
    id: 66,
    name: 'npc_dota_hero_chen',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/chen.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/chen.png?',
    localized_name: 'Chen',
  },
  {
    id: 67,
    name: 'npc_dota_hero_spectre',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Durable', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/spectre.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/spectre.png?',
    localized_name: 'Spectre',
  },
  {
    id: 68,
    name: 'npc_dota_hero_ancient_apparition',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/ancient_apparition.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/ancient_apparition.png?',
    localized_name: 'Ancient Apparition',
  },
  {
    id: 69,
    name: 'npc_dota_hero_doom_bringer',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/doom_bringer.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/doom_bringer.png?',
    localized_name: 'Doom',
  },
  {
    id: 70,
    name: 'npc_dota_hero_ursa',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Durable', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/ursa.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/ursa.png?',
    localized_name: 'Ursa',
  },
  {
    id: 71,
    name: 'npc_dota_hero_spirit_breaker',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Initiator', 'Disabler', 'Durable', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/spirit_breaker.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/spirit_breaker.png?',
    localized_name: 'Spirit Breaker',
  },
  {
    id: 72,
    name: 'npc_dota_hero_gyrocopter',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/gyrocopter.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/gyrocopter.png?',
    localized_name: 'Gyrocopter',
  },
  {
    id: 73,
    name: 'npc_dota_hero_alchemist',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Support', 'Durable', 'Disabler', 'Initiator', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/alchemist.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/alchemist.png?',
    localized_name: 'Alchemist',
  },
  {
    id: 74,
    name: 'npc_dota_hero_invoker',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler', 'Escape', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/invoker.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/invoker.png?',
    localized_name: 'Invoker',
  },
  {
    id: 75,
    name: 'npc_dota_hero_silencer',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Support', 'Disabler', 'Initiator', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/silencer.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/silencer.png?',
    localized_name: 'Silencer',
  },
  {
    id: 76,
    name: 'npc_dota_hero_obsidian_destroyer',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/obsidian_destroyer.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/obsidian_destroyer.png?',
    localized_name: 'Outworld Devourer',
  },
  {
    id: 77,
    name: 'npc_dota_hero_lycan',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Carry', 'Pusher', 'Durable', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/lycan.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/lycan.png?',
    localized_name: 'Lycan',
  },
  {
    id: 78,
    name: 'npc_dota_hero_brewmaster',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Carry', 'Initiator', 'Durable', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/brewmaster.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/brewmaster.png?',
    localized_name: 'Brewmaster',
  },
  {
    id: 79,
    name: 'npc_dota_hero_shadow_demon',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Initiator', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/shadow_demon.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/shadow_demon.png?',
    localized_name: 'Shadow Demon',
  },
  {
    id: 80,
    name: 'npc_dota_hero_lone_druid',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Carry', 'Pusher', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/lone_druid.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/lone_druid.png?',
    localized_name: 'Lone Druid',
  },
  {
    id: 81,
    name: 'npc_dota_hero_chaos_knight',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Disabler', 'Durable', 'Pusher', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/chaos_knight.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/chaos_knight.png?',
    localized_name: 'Chaos Knight',
  },
  {
    id: 82,
    name: 'npc_dota_hero_meepo',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker', 'Disabler', 'Initiator', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/meepo.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/meepo.png?',
    localized_name: 'Meepo',
  },
  {
    id: 83,
    name: 'npc_dota_hero_treant',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Support', 'Initiator', 'Durable', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/treant.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/treant.png?',
    localized_name: 'Treant Protector',
  },
  {
    id: 84,
    name: 'npc_dota_hero_ogre_magi',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Support', 'Nuker', 'Disabler', 'Durable', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/ogre_magi.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/ogre_magi.png?',
    localized_name: 'Ogre Magi',
  },
  {
    id: 85,
    name: 'npc_dota_hero_undying',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Support', 'Durable', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/undying.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/undying.png?',
    localized_name: 'Undying',
  },
  {
    id: 86,
    name: 'npc_dota_hero_rubick',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/rubick.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/rubick.png?',
    localized_name: 'Rubick',
  },
  {
    id: 87,
    name: 'npc_dota_hero_disruptor',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/disruptor.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/disruptor.png?',
    localized_name: 'Disruptor',
  },
  {
    id: 88,
    name: 'npc_dota_hero_nyx_assassin',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Disabler', 'Nuker', 'Initiator', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/nyx_assassin.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/nyx_assassin.png?',
    localized_name: 'Nyx Assassin',
  },
  {
    id: 89,
    name: 'npc_dota_hero_naga_siren',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Support', 'Pusher', 'Disabler', 'Initiator', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/naga_siren.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/naga_siren.png?',
    localized_name: 'Naga Siren',
  },
  {
    id: 90,
    name: 'npc_dota_hero_keeper_of_the_light',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/keeper_of_the_light.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/keeper_of_the_light.png?',
    localized_name: 'Keeper of the Light',
  },
  {
    id: 91,
    name: 'npc_dota_hero_wisp',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/wisp.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/wisp.png?',
    localized_name: 'Io',
  },
  {
    id: 92,
    name: 'npc_dota_hero_visage',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Durable', 'Disabler', 'Pusher'],
    img: '/apps/dota2/images/dota_react/heroes/visage.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/visage.png?',
    localized_name: 'Visage',
  },
  {
    id: 93,
    name: 'npc_dota_hero_slark',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/slark.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/slark.png?',
    localized_name: 'Slark',
  },
  {
    id: 94,
    name: 'npc_dota_hero_medusa',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Disabler', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/medusa.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/medusa.png?',
    localized_name: 'Medusa',
  },
  {
    id: 95,
    name: 'npc_dota_hero_troll_warlord',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Pusher', 'Disabler', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/troll_warlord.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/troll_warlord.png?',
    localized_name: 'Troll Warlord',
  },
  {
    id: 96,
    name: 'npc_dota_hero_centaur',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Durable', 'Initiator', 'Disabler', 'Nuker', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/centaur.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/centaur.png?',
    localized_name: 'Centaur Warrunner',
  },
  {
    id: 97,
    name: 'npc_dota_hero_magnataur',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Initiator', 'Disabler', 'Nuker', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/magnataur.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/magnataur.png?',
    localized_name: 'Magnus',
  },
  {
    id: 98,
    name: 'npc_dota_hero_shredder',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Nuker', 'Durable', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/shredder.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/shredder.png?',
    localized_name: 'Timbersaw',
  },
  {
    id: 99,
    name: 'npc_dota_hero_bristleback',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Durable', 'Initiator', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/bristleback.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/bristleback.png?',
    localized_name: 'Bristleback',
  },
  {
    id: 100,
    name: 'npc_dota_hero_tusk',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Initiator', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/tusk.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/tusk.png?',
    localized_name: 'Tusk',
  },
  {
    id: 101,
    name: 'npc_dota_hero_skywrath_mage',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/skywrath_mage.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/skywrath_mage.png?',
    localized_name: 'Skywrath Mage',
  },
  {
    id: 102,
    name: 'npc_dota_hero_abaddon',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Support', 'Carry', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/abaddon.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/abaddon.png?',
    localized_name: 'Abaddon',
  },
  {
    id: 103,
    name: 'npc_dota_hero_elder_titan',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Initiator', 'Disabler', 'Nuker', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/elder_titan.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/elder_titan.png?',
    localized_name: 'Elder Titan',
  },
  {
    id: 104,
    name: 'npc_dota_hero_legion_commander',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/legion_commander.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/legion_commander.png?',
    localized_name: 'Legion Commander',
  },
  {
    id: 105,
    name: 'npc_dota_hero_techies',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/techies.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/techies.png?',
    localized_name: 'Techies',
  },
  {
    id: 106,
    name: 'npc_dota_hero_ember_spirit',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker', 'Disabler', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/ember_spirit.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/ember_spirit.png?',
    localized_name: 'Ember Spirit',
  },
  {
    id: 107,
    name: 'npc_dota_hero_earth_spirit',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Nuker', 'Escape', 'Disabler', 'Initiator', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/earth_spirit.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/earth_spirit.png?',
    localized_name: 'Earth Spirit',
  },
  {
    id: 108,
    name: 'npc_dota_hero_abyssal_underlord',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Support', 'Nuker', 'Disabler', 'Durable', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/abyssal_underlord.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/abyssal_underlord.png?',
    localized_name: 'Underlord',
  },
  {
    id: 109,
    name: 'npc_dota_hero_terrorblade',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Pusher', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/terrorblade.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/terrorblade.png?',
    localized_name: 'Terrorblade',
  },
  {
    id: 110,
    name: 'npc_dota_hero_phoenix',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Initiator', 'Escape', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/phoenix.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/phoenix.png?',
    localized_name: 'Phoenix',
  },
  {
    id: 111,
    name: 'npc_dota_hero_oracle',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/oracle.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/oracle.png?',
    localized_name: 'Oracle',
  },
  {
    id: 112,
    name: 'npc_dota_hero_winter_wyvern',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/winter_wyvern.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/winter_wyvern.png?',
    localized_name: 'Winter Wyvern',
  },
  {
    id: 113,
    name: 'npc_dota_hero_arc_warden',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Carry', 'Escape', 'Nuker'],
    img: '/apps/dota2/images/dota_react/heroes/arc_warden.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/arc_warden.png?',
    localized_name: 'Arc Warden',
  },
  {
    id: 114,
    name: 'npc_dota_hero_monkey_king',
    primary_attr: 'agi',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Disabler', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/monkey_king.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/monkey_king.png?',
    localized_name: 'Monkey King',
  },
  {
    id: 119,
    name: 'npc_dota_hero_dark_willow',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/dark_willow.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/dark_willow.png?',
    localized_name: 'Dark Willow',
  },
  {
    id: 120,
    name: 'npc_dota_hero_pangolier',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Carry', 'Nuker', 'Disabler', 'Durable', 'Escape', 'Initiator'],
    img: '/apps/dota2/images/dota_react/heroes/pangolier.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/pangolier.png?',
    localized_name: 'Pangolier',
  },
  {
    id: 121,
    name: 'npc_dota_hero_grimstroke',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/grimstroke.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/grimstroke.png?',
    localized_name: 'Grimstroke',
  },
  {
    id: 123,
    name: 'npc_dota_hero_hoodwink',
    primary_attr: 'agi',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Escape', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/hoodwink.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/hoodwink.png?',
    localized_name: 'Hoodwink',
  },
  {
    id: 126,
    name: 'npc_dota_hero_void_spirit',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/void_spirit.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/void_spirit.png?',
    localized_name: 'Void Spirit',
  },
  {
    id: 128,
    name: 'npc_dota_hero_snapfire',
    primary_attr: 'all',
    attack_type: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/snapfire.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/snapfire.png?',
    localized_name: 'Snapfire',
  },
  {
    id: 129,
    name: 'npc_dota_hero_mars',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Initiator', 'Disabler', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/mars.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/mars.png?',
    localized_name: 'Mars',
  },
  {
    id: 135,
    name: 'npc_dota_hero_dawnbreaker',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Carry', 'Durable'],
    img: '/apps/dota2/images/dota_react/heroes/dawnbreaker.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/dawnbreaker.png?',
    localized_name: 'Dawnbreaker',
  },
  {
    id: 136,
    name: 'npc_dota_hero_marci',
    primary_attr: 'all',
    attack_type: 'Melee',
    roles: ['Support', 'Carry', 'Initiator', 'Disabler', 'Escape'],
    img: '/apps/dota2/images/dota_react/heroes/marci.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/marci.png?',
    localized_name: 'Marci',
  },
  {
    id: 137,
    name: 'npc_dota_hero_primal_beast',
    primary_attr: 'str',
    attack_type: 'Melee',
    roles: ['Initiator', 'Durable', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/primal_beast.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/primal_beast.png?',
    localized_name: 'Primal Beast',
  },
  {
    id: 138,
    name: 'npc_dota_hero_muerta',
    primary_attr: 'int',
    attack_type: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler'],
    img: '/apps/dota2/images/dota_react/heroes/muerta.png?',
    icon: '/apps/dota2/images/dota_react/heroes/icons/muerta.png?',
    localized_name: 'Muerta',
  },
];
